spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/bd_biblioteca
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true